import { Ubuntu } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={dark}>
      <html lang="en">
        <body className={ubuntu.className}>
          {/* <ClerkLoading>
            <div className="bg-[--bg]">
              <Loader />
            </div>
          </ClerkLoading> */}

          <div className="flex flex-col justify-between min-h-screen bg-[--bg] ">
            {/* <ClerkLoaded> */}
            <Navbar />
            <Toaster />
            {children}
            <Footer />
            {/* </ClerkLoaded> */}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
